#!/usr/bin/env python3

import sys
import os
import helpers

from analyzer import Analyzer
from termcolor import colored

def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        print("Usage: ./tweets @handle")
        exit(1)
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")
    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    user = sys.argv[1].lstrip('@')
    
    tweets = helpers.get_user_timeline(user, 50)
    
    if tweets is None:
        print("Restricted account or does not exist")
        exit(2)
    else:
        for tweet in tweets:
            score = analyzer.analyze(tweet)
            if score > 0.0:
                print(colored(score, "green"), colored(tweet, "green"))
            elif score < 0.0:
                print(colored(score, "red"), colored(tweet, "red"))
            else:
                print(colored(score, "yellow"), colored(tweet, "yellow"))
        
if __name__ == "__main__":
    main()